### ISSUE TITLE
Development instructions needed

### ISSUE THREAD

**Issue by mattboardman** [rmohr/bazeldnf#57] opened 2023-05-28 15:50 UTC
I wanted to add a feature for different allowed checksum types (such as sha1) that might be used for certain RPM repos. However I am unable to build all the targets on `main`.

### Steps to reproduce 

1. Open a new codespace.
2. Install bazelisk and bazel
3. run `bazel build //...`
4. Bazel errors out

```
Starting local Bazel server and connecting to it...
INFO: Repository bazel_gazelle_go_repository_tools instantiated at:
  /workspaces/bazeldnf/WORKSPACE:63:21: in <toplevel>
  /home/codespace/.cache/bazel/_bazel_codespace/41a0baffe935881d80be720d73400e18/external/bazel_gazelle/deps.bzl:75:24: in gazelle_dependencies
Repository rule go_repository_tools defined at:
  /home/codespace/.cache/bazel/_bazel_codespace/41a0baffe935881d80be720d73400e18/external/bazel_gazelle/internal/go_repository_tools.bzl:117:38: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':
   Traceback (most recent call last):
        File "/home/codespace/.cache/bazel/_bazel_codespace/41a0baffe935881d80be720d73400e18/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
                fail("failed to build tools: " + result.stderr)
Error in fail: failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /home/codespace/.cache/bazel/_bazel_codespace/41a0baffe935881d80be720d73400e18/external/go_sdk/pkg/tool/linux_amd64/compile: signal: killed
ERROR: /workspaces/bazeldnf/WORKSPACE:63:21: fetching go_repository_tools rule //external:bazel_gazelle_go_repository_tools: Traceback (most recent call last):
        File "/home/codespace/.cache/bazel/_bazel_codespace/41a0baffe935881d80be720d73400e18/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
                fail("failed to build tools: " + result.stderr)
Error in fail: failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /home/codespace/.cache/bazel/_bazel_codespace/41a0baffe935881d80be720d73400e18/external/go_sdk/pkg/tool/linux_amd64/compile: signal: killed
ERROR: error loading package '': Encountered error while reading extension file 'buildifier/def.bzl': no such package '@com_github_bazelbuild_buildtools//buildifier': no such package '@bazel_gazelle_go_repository_config//': no such package '@bazel_gazelle_go_repository_tools//': failed to build tools: go build github.com/bazelbuild/bazel-gazelle/language/proto: /home/codespace/.cache/bazel/_bazel_codespace/41a0baffe935881d80be720d73400e18/external/go_sdk/pkg/tool/linux_amd64/compile: signal: killed
INFO: Elapsed time: 50.129s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (13 packages loaded)
    currently loading: 
    Fetching @com_github_bazelbuild_buildtools; Restarting. 40s
    Fetching @bazel_gazelle_go_repository_config; Restarting. 40s
```

A development README would be helpful in this case since I'm not sure how to build all the targets.

**Comment by rmohr** [comment] 2023-06-01 09:58
Hi Matt,

I think the issue is, that you are not using `bazelisk`. It just used the bazel installation which you have on your system.

You can either run `bazelisk build //...`, or manually ensure that your `bazel` binary matches `cat .bazelversion` in the repo, wich is right now `5.1.0`.

I personally don't have bazel installed on my machine. Instead I just have a symlink from `bazel` to `bazelisk`. `bazelisk` will automatically use the right bazel version then and I don't have to care about calling `bazelisk`.

**Comment by rmohr** [comment] 2023-06-01 09:59
And doubl-checked:

```
bazelisk build //...
```

should build fine.

**Comment by rmohr** [comment] 2023-06-01 10:09
btw. a custom implementation of  this function may be  necessary to make other shausms work: https://bazel.build/rules/lib/builtins/module_ctx#download. But not sure about automatic caching implications actually.

**Comment by rmohr** [comment] 2023-10-06 21:58
Closing this for now. Feel free to reopen if needed.

**Closed by rmohr** 2023-10-06 21:58 UTC
